In [1]:
import numpy as np
A=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
B=np.array([[4],
   [5],
   [6]])
C=2*np.matmul(A,B)
print(C)



[[ 64]
 [154]
 [244]]


In [11]:
import numpy as np
A=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
A2=np.linalg.matrix_power(A,3)
C=A+A2
C=np.sin(C)
print(C)

[[-0.78499906 -0.05302338  0.84618828]
 [-0.84151984  0.04412222  0.88586888]
 [-0.89006432 -0.03521755  0.91994333]]


In [12]:
import numpy as np
A=np.array([[1,2,3],
   [4,5j,6],
   [7,8,9]])
A2=np.linalg.matrix_power(A,3)
C=A+A2
C=np.absolute(C)
print(C)

[[ 430.86076637  371.4888962   629.86427109]
 [ 676.31057954  760.26311235  981.16053732]
 [1511.49230895 1286.01866238 2194.16521712]]


In [15]:
import numpy as np
x=np.array([1,2,3])
y=np.array([1,0,1])
C=np.matmul(x,y)
print(C)
D=np.dot(y,x)
print(D)


4
4


In [4]:
import numpy as np
x= np.array([1,2,3])
y= np.array([1,0,1])
z1=np.outer(x,y)
z2=np.inner(y,x)
print(z1)
print(z2)

[[1 0 1]
 [2 0 2]
 [3 0 3]]
4


In [5]:
import numpy as np
x= np.array([1,2,3])
y= np.array([1,0,1])
x=np.reshape(x,(3,1))
y=np.reshape(y,(1,3))
z1=np.dot(x,y)
z2=np.dot(y,x)
print(z1)
print(z2)

[[1 0 1]
 [2 0 2]
 [3 0 3]]
[[4]]


In [19]:
import numpy as np
x=0.85
y=2
diagonal=np.array([x,x*y,x/y])
dmatrix=np.diag(diagonal)
print(dmatrix)

[[0.85  0.    0.   ]
 [0.    1.7   0.   ]
 [0.    0.    0.425]]


In [22]:
import numpy as np
x=np.array([2,7,12,17,22,27,32])
x=np.square(x)
z=np.sum(x)
print(z)



2723


In [23]:
import numpy as np
x = np.random.randint(0, 10, size=(3, 3))
print(x)
y=np.sort(x, axis=None)
print(y)



[[6 8 7]
 [4 6 6]
 [5 7 4]]
[4 4 5 6 6 6 7 7 8]


In [24]:
import numpy as np
x = np.random.randint(0, 10, size=(3, 2,2))
print(x)
y=np.sort(x, axis=None)
print(y)

[[[6 7]
  [7 2]]

 [[3 4]
  [8 3]]

 [[5 2]
  [2 2]]]
[2 2 2 2 3 3 4 5 6 7 7 8]


In [25]:
import numpy as np
x=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
y=np.resize(x,(3,8))
print(y)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


In [27]:
import numpy as np
x=np.array([1,2,3])
y=np.array([12,15,18])
dp=np.dot(x,y)
exponential=np.exp(dp)
print(exponential)

4.923458286012058e+41


In [28]:
import numpy as np
x1=np.array([0,2,3])
x2=np.array([1,2,2])
cross=np.cross(x1,x2)
area=np.linalg.norm(cross)
print(area)

4.123105625617661


In [1]:
import numpy as np
x=np.array([[1,2,0],
   [2,7,1],
   [0,0,5]])
y=np.array=([[1],
            [2],
            [3]])
z=np.matmul(np.transpose(y),x)
z=np.matmul(z,y)
print(z)
w=np.matmul(y,np.transpose(y))
print(w)

[[88]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [7]:
import numpy as np
x=np.array([[1,2,0],
   [2,7,1],
   [0,0,5]])
with open("array_elements.txt", "w") as file:
    for row in x:
        file.write(" ".join(str(element) for element in row))
        file.write("\n")

with open("array_elements.txt", "r") as file:
    lines = file.readlines()
    y = np.array([list(map(int, line.strip().split())) for line in lines])
z = x - y
print(x)
print(y)
print(z)

[[1 2 0]
 [2 7 1]
 [0 0 5]]
[[1 2 0]
 [2 7 1]
 [0 0 5]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
